# Generated by Django 6.1.1 on 2026-10-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='core.estado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ('estado__nombre', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parroquias', to='core.municipio')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'ordering': ('municipio__estado__nombre', 'municipio__nombre', 'nombre'),
            },
        ),
        migrations.AddConstraint(
            model_name='municipio',
            constraint=models.UniqueConstraint(fields=('estado', 'nombre'), name='uq_municipio_estado_nombre'),
        ),
        migrations.AddConstraint(
            model_name='parroquia',
            constraint=models.UniqueConstraint(fields=('municipio', 'nombre'), name='uq_parroquia_municipio_nombre'),
        ),
    ]
