# Generated by Django 6.1.1 on 2026-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='codigo',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
