# Generated by Django 6.1.1 on 2026-10-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_municipio_codigo_parroquia_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
