# Generated by Django 6.1.1 on 2026-10-07 07:17

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('unidad', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='CentroAyuda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('LOGISTICO', 'Logístico'), ('DISTRIBUCION', 'Distribución'), ('COORDINACION', 'Coordinación'), ('MIXTO', 'Mixto')], db_index=True, default='MIXTO', max_length=20)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('capacidad', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_ayuda', to='core.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_ayuda', to='core.municipio')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_ayuda', to='core.parroquia')),
            ],
            options={
                'verbose_name': 'Centro de ayuda',
                'verbose_name_plural': 'Centros de ayuda',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimo', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='operaciones.centroayuda')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='operaciones.recurso')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ('centro__nombre', 'recurso__nombre'),
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], db_index=True, max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='operaciones.inventario')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('capacidad', models.PositiveIntegerField(default=0)),
                ('ocupacion', models.PositiveIntegerField(default=0)),
                ('estado_operativo', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('COMPLETO', 'Completo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento')], db_index=True, default='DISPONIBLE', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refugios', to='core.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refugios', to='core.municipio')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refugios', to='core.parroquia')),
            ],
            options={
                'verbose_name': 'Refugio',
                'verbose_name_plural': 'Refugios',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta'), ('AMBULANCIA', 'Ambulancia'), ('AUTOBUS', 'Autobús'), ('OTRO', 'Otro')], max_length=20)),
                ('estado_operativo', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_RUTA', 'En ruta'), ('MANTENIMIENTO', 'Mantenimiento'), ('INACTIVO', 'Inactivo')], db_index=True, default='DISPONIBLE', max_length=20)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='operaciones.centroayuda')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_conducidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ('placa',),
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('estado_mision', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('ASIGNADA', 'Asignada'), ('EN_RUTA', 'En ruta'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PLANIFICADA', max_length=20)),
                ('modo_ruta', models.CharField(choices=[('MAS_CORTA', 'Más corta'), ('MAS_RAPIDA', 'Más rápida'), ('MAS_SEGURA', 'Más segura'), ('HUMANITARIA', 'Humanitaria')], db_index=True, default='HUMANITARIA', max_length=20)),
                ('origen', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destino', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('prioridad', models.PositiveSmallIntegerField(default=1, help_text='Prioridad de 1 a 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_estimado_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('ruta', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('planificada_en', models.DateTimeField(auto_now_add=True)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('entregada_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones_coordinadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones', to='operaciones.vehiculo')),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misiones',
                'ordering': ('-planificada_en',),
            },
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('geometria', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('estado_vial', models.CharField(choices=[('NORMAL', 'Normal'), ('PRECAUCION', 'Precaución'), ('AFECTADA', 'Afectada'), ('CRITICA', 'Crítica'), ('CERRADA', 'Cerrada')], db_index=True, default='NORMAL', max_length=20)),
                ('velocidad_referencial', models.PositiveSmallIntegerField(blank=True, help_text='Velocidad referencial en km/h.', null=True)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vias', to='core.estado')),
            ],
            options={
                'verbose_name': 'Vía',
                'verbose_name_plural': 'Vías',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='ReporteVial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ACCIDENTE', 'Accidente'), ('INUNDACION', 'Inundación'), ('DERRUMBE', 'Derrumbe'), ('CIERRE', 'Cierre'), ('PUENTE_DANADO', 'Puente dañado'), ('OBSTACULO', 'Obstáculo'), ('PROTESTA', 'Protesta'), ('TRAFICO', 'Tráfico'), ('OBRAS', 'Obras'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('estado_reporte', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado'), ('RESUELTO', 'Resuelto')], db_index=True, default='PENDIENTE', max_length=20)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('severidad', models.PositiveSmallIntegerField(default=1, help_text='Nivel de severidad de 1 a 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reportado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_viales', to=settings.AUTH_USER_MODEL)),
                ('via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='operaciones.via')),
            ],
            options={
                'verbose_name': 'Reporte vial',
                'verbose_name_plural': 'Reportes viales',
                'ordering': ('-reportado_en',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(db_index=True, max_length=100)),
                ('modulo', models.CharField(db_index=True, max_length=100)),
                ('objeto_tipo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error'), ('RECHAZADO', 'Rechazado')], db_index=True, default='EXITO', max_length=12)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ('-fecha',),
                'indexes': [models.Index(fields=['modulo', 'accion', 'fecha'], name='operaciones_modulo_ee7a48_idx'), models.Index(fields=['usuario', 'fecha'], name='operaciones_usuario_6ef49f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='centroayuda',
            index=models.Index(fields=['tipo', 'activo'], name='operaciones_tipo_433734_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo', 'creado_en'], name='operaciones_tipo_9264a7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['centro', 'recurso'], name='operaciones_centro__fbe1ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.UniqueConstraint(fields=('centro', 'recurso'), name='uq_inventario_centro_recurso'),
        ),
        migrations.AddIndex(
            model_name='refugio',
            index=models.Index(fields=['estado_operativo', 'activo'], name='operaciones_estado__6c487b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['estado_operativo', 'activo'], name='operaciones_estado__af4511_idx'),
        ),
        migrations.AddIndex(
            model_name='mision',
            index=models.Index(fields=['estado_mision', 'modo_ruta'], name='operaciones_estado__ac20a4_idx'),
        ),
        migrations.AddIndex(
            model_name='mision',
            index=models.Index(fields=['prioridad', 'estado_mision'], name='operaciones_priorid_59f658_idx'),
        ),
        migrations.AddIndex(
            model_name='via',
            index=models.Index(fields=['estado_vial', 'activa'], name='operaciones_estado__96c5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportevial',
            index=models.Index(fields=['tipo', 'estado_reporte'], name='operaciones_tipo_3b2173_idx'),
        ),
        migrations.AddIndex(
            model_name='reportevial',
            index=models.Index(fields=['reportado_en'], name='operaciones_reporta_cdb272_idx'),
        ),
    ]
