# Generated by Django 6.1.1 on 2026-10-07 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mision',
            constraint=models.CheckConstraint(condition=models.Q(('prioridad__gte', 1), ('prioridad__lte', 5)), name='ck_mision_prioridad_valida'),
        ),
        migrations.AddConstraint(
            model_name='refugio',
            constraint=models.CheckConstraint(condition=models.Q(('ocupacion__gte', 0), ('ocupacion__lte', models.F('capacidad'))), name='ck_refugio_ocupacion_valida'),
        ),
        migrations.AddConstraint(
            model_name='reportevial',
            constraint=models.CheckConstraint(condition=models.Q(('severidad__gte', 1), ('severidad__lte', 5)), name='ck_reporte_vial_severidad_valida'),
        ),
    ]
